### PR TITLE
Vectara Component Update - feature enhancement

### PR DESCRIPTION
**Pull request by JAtharva22**
### Pull Request for Issue #1217 
[feature request](https://github.com/logspace-ai/langflow/labels/feature%20request)
[python](https://github.com/logspace-ai/langflow/labels/python)

**Description**
This pull request addresses issue #1217 , which concerns the ability to add files directly to the Vectara vector store using the indexing API's file upload feature.

**Changes Made**
I have implemented the ability to add files directly to the Vectara vector store by providing URLs of documents online. The add_files() method (as well as from_files()) has been added to facilitate this functionality.

**Files Modified/Added**
Modified: vectara.py

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
@JAtharva22  Could you respond to my review so we can merge this PR? Let me know if there's anything I can help you with.

**Comment by JAtharva22** [comment]
> @JAtharva22 Could you respond to my review so we can merge this PR? Let me know if there's anything I can help you with.

@ogabrielluiz hey thanks for replying
I just couldn't see your review anywhere. Could you please in anyway link it to me?

**Comment by ogabrielluiz** [comment]
> > @JAtharva22 Could you respond to my review so we can merge this PR? Let me know if there's anything I can help you with.
> 
> @ogabrielluiz hey thanks for replying
> I just couldn't see your review anywhere. Could you please in anyway link it to me?

https://github.com/logspace-ai/langflow/pull/1219#discussion_r1433960160

**Comment by JAtharva22** [comment]
> > > @JAtharva22 Could you respond to my review so we can merge this PR? Let me know if there's anything I can help you with.
> > 
> > 
> > @ogabrielluiz hey thanks for replying
> > I just couldn't see your review anywhere. Could you please in anyway link it to me?
> 
> [#1219 (comment)](https://github.com/logspace-ai/langflow/pull/1219#discussion_r1433960160)

Sorry but I still cannot see any reviews. Can you please check again if you submitted any reviews?

**Comment by ogabrielluiz** [comment]
I asked about the use of FakeEmbeddings. You should probably expose it as a parameter. Why did you choose to use the FakeEmbeddings?

**Comment by JAtharva22** [comment]
Actually, I spoke with one of the devs at vectara and they told me that even if user gives their own embeddings as input to the function, vectara will use its own embeddings. And also, the embeddings parameter is compulsory parameter for the from_files function. Without it, it throws an error.
So regardless of if the user inputs embeddings or not, vectara is going to use its own embeddings anyways. So I decided to use FakeEmbeddings as they referenced in their langchain documentation - [https://python.langchain.com/docs/integrations/vectorstores/vectara](url)

> I asked about the use of FakeEmbeddings. You should probably expose it as a parameter. Why did you choose to use the FakeEmbeddings?

**Review by ogabrielluiz — APPROVED** [review]
LGTM

**Pull request merged**
