### PR TITLE
migrating to Vite

### PR DESCRIPTION
**Pull request by gsaivinay**
This PR implements #264

### Changes done

- Organized package.json for dev only dependencies.
- Removed react-scripts and added Vite and its dependencies.
- Refactored `require` with `import` in few places.

### Changes to development process

- Most of the development workflow is unchanged with this migration.
- For any API call to backend, the path must be added in the `vite.config.ts` so that vite server can forward it to backend server via proxy. This can be standardized with naming conventions so that we can simply configure regular expressions and forget about it.

### Testing

- [x] Build and test
- [x] Run dev servers and test

### CODE REVIEW

**Comment by gsaivinay** [comment]
@ogabrielluiz - I created new PR from the same branch, as the previous one showing lot of commits and diff after rebase. Once the tests are done and there is enough confidence, we can merge.

**Comment by ogabrielluiz** [comment]
I'll run the tests ASAP, probably today. I'm sure it will be work, though =) Thanks for the help @gsaivinay

**Comment by ogabrielluiz** [comment]
LGTM

**Review by ogabrielluiz — APPROVED** [review]

**Comment by ogabrielluiz** [comment]
Closes #264

**Pull request merged**
