### PR TITLE
Anthropic

### PR DESCRIPTION
**Pull request by jimwhite**
Add basic support for Anthropic LLM and Chat model.   

Not totally sure the Anthropic LLM needs support because the [docs](https://github.com/hwchase17/langchain/blob/20ec1173f40a13cba73d79cc0efa4653d2489d65/langchain/llms/anthropic.py#L128) say it is deprecated.  But if that is removed do we call the Chat model ChatAnthropic or just Anthropic?

I just made a [PR](https://github.com/hwchase17/langchain/pull/5628) for langchain to change their Anthropic classes to use the same property names as the other llms and chat models so model_name and max_tokens will work with LangFlow.

The relevant issue here is [https://github.com/logspace-ai/langflow/issues/290](https://github.com/logspace-ai/langflow/issues/290)

The reason I worked on this is we're using LangFlow in our LabLabAI Anthropic hackathon demo: [https://lablab.ai/event/anthropic-ai-hackathon](https://lablab.ai/event/anthropic-ai-hackathon)

### CODE REVIEW

**Comment by jimwhite** [comment]
The relevant issue here is [https://github.com/logspace-ai/langflow/issues/290](https://github.com/logspace-ai/langflow/issues/290)

**Comment by ogabrielluiz** [comment]
Hey, @jimwhite 
We haven't added it because I don't have access yet. Were you able to test it?

**Review by ogabrielluiz — APPROVED** [review]
LGTM

**Comment by jimwhite** [comment]
Yes, it works.  Trouble is that Claude doesn't work very well with prompts that work fine with GPT for things like Document Q&A.  I'll be looking into how to fix the prompts.

Thanks for the quick merge.  I'm on another hackathon that just started today [ethglobal.com/events/hackfs2023](https://ethglobal.com/events/hackfs2023) and I'm planning to build a demo for running LangFlow LangChains on Web3 for at least sharing the data and possibly for running the chains too.

**Comment by ogabrielluiz** [comment]
Awesome!

**Pull request merged**
