### PR TITLE
Fix: Dynamic tooltipTitle, id mapping bugfix for last ParameterCompon…

### PR DESCRIPTION
**Pull request by ScripterSugar**
Resolving #47 

I'm not touching hard-coded `type={'str'}` line here because I'm not certain about its side-effects.
It must be addressed as separated issue IMO.

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
LGTM.

@lucaseduoli, you?

**Review by ogabrielluiz — COMMENTED** [review]
This fixes the issue of not being able to connect OpenAI to tools

**Comment by ogabrielluiz** [comment]
@ScripterSugar we'll merge into dev and prepare a release for today asap.

**Comment by lucaseduoli** [comment]
LGTM, thanks for the contribution! All my tests passed too.

**Pull request merged**
