### PR TITLE
Add Import Examples Feature to Flow Editor

### PR DESCRIPTION
**Pull request by anovazzi1**
This pull request adds a new feature to the flow editor that allows users to easily import example flows from the [logspace-ai/langflow_examples](https://github.com/logspace-ai/langflow_examples) repository on GitHub. The feature is accessible via the import example button

Clicking on the "Import Examples" button opens a dialog box that displays a list of available example flows from the GitHub repository. Users can select one example to import, and the flow editor will automatically add the selected flow to the user's current project.

This feature saves users time and effort by providing a convenient way to explore and utilize pre-built flows.

Additionally, this feature promotes collaboration and community involvement by encouraging users to contribute their own flows to the repository for others to use and benefit from.

### CODE REVIEW

**Review by ogabrielluiz — CHANGES_REQUESTED** [review]
We can set the color of the example cards to be the same as the card in the previous page (the first import popup). 

Also,  we should add a link to the examples repo. Maybe a github icon in the bottom right? What do you think?

Also, the text in the popup is "Import from", so we need to fix that.

**Comment by Ryangr0** [comment]
Hey guys, just came across this project. Is there anything I can do to help? I'm working on implementing several langchain features together and I'd like to import my current project. I'd love to see a visual representation of it.

**Comment by ogabrielluiz** [comment]
Hey, @Ryangr0 could you open a discussion for us to talk there? I'm not sure I follow what you asked.

**Comment by ogabrielluiz** [comment]
@anovazzi1 The button should probably be in the middle like:
`LangFlow Examples [icon]` and have an outline to indicate it is a button.

Can the text in the cards be justified center? It seems the word Conversational is a bit off.

**Pull request merged**
