### PR TITLE
Correct run instructions in Readme

### PR DESCRIPTION
**Pull request by PaulLockett**
Fix this for future users so they can get it up and running without having to probe the  GitHub forum

### CODE REVIEW

**Comment by PaulLockett** [comment]
@ogabrielluiz  I did not set up a conda enviroment. I just did the pip install so there is no cli comand named `langflow.` and `python langflow` does not work.

If the idea case is to make a conda enviroment please add that to the readme.

**Review by ogabrielluiz — CHANGES_REQUESTED** [review]
Please, use the code block and add both commands and this should be good to go.

**Comment by ogabrielluiz** [comment]
The conda environment is used to isolate the installation to make the test more reliable.

**Comment by mausch** [comment]
FWIW the current instructions work for me, just 

```
pip install langflow
langflow
```

**Comment by twardoch** [comment]
You can pick any Python installer to install and then to run: 

1. Install

python3 -m pip install --upgrade langflow

2. Run

python3 -m langflow

**Comment by ogabrielluiz** [comment]
Yes. Having both options displayed looks good to me.

**Review by ogabrielluiz — APPROVED** [review]

**Pull request merged**
