### PR TITLE
Add SearchApi integration

### PR DESCRIPTION
**Pull request by SebastjanPrachovskij**
SearchApi is ready to invest in AI and LLM space, especially open-source development.

We already have a Flowise integration, so this would be a great addition on the Python side. 🎉 

Feel free to assign @SebastjanPrachovskij as a main reviewer for any SearchApi-related searches. We will be glad to help and support langflow development.

### CODE REVIEW

**Review by ogabrielluiz — COMMENTED** [review]
Hey @SebastjanPrachovskij 

LGTM.

Btw, maybe we should expand on this. Have a component in the langflow.store or something like that. What do you say?

**Comment by SebastjanPrachovskij** [comment]
Hey @ogabrielluiz 

Thanks, we can expand with the langflow.store example. BTW, a simple usage example has already been added to the documentation.

Should langflow.store examples be added through the UI? Can you also approve my waitlist (seb@searchapi.io)? 

---
It is worth noting that we experienced some issues that might prevent us from crafting advanced usage scenarios. For instance, [Flowise](https://github.com/FlowiseAI/Flowise/pull/1162) has a YouTube Transcripts summarization example.

1. We tried adding [SearchApiAPIWrapper](https://github.com/logspace-ai/langflow/blob/7c79bacdc231c415ccdcadd760e36db60c8bd12c/src/backend/langflow/config.yaml#L260)  to the config, but it is not visible in Langflow UI. Do you know why?

2. Is it possible to pass custom parameters such as engine and the whole JSON (for instance, youtube_transcripts engine requires video_id)? [LangChain code](https://github.com/langchain-ai/langchain/blob/a0ec04549575de5547faa5381fa69fef61405ac8/libs/community/langchain_community/utilities/searchapi.py) 

Appreciate the help. 🤗

**Comment by ogabrielluiz** [comment]
Hey @SebastjanPrachovskij 

I've added you to the waitlist.

About the parameters, you can define a CustomComponent which allows you to define pretty much anything.

You can check out more details here: https://docs.langflow.org/components/custom

Also, you can check out many examples in the src/backend/langflow/components folder.

**Comment by SebastjanPrachovskij** [comment]
Hey @ogabrielluiz 

I've added the `SearchApi` tool-using `CustomComponent`; now the user can pass any parameter to it. Thanks for the advice!

Regarding the store, do you think we should expand it after the merge or I should add it manually somehow? Right now there's a `SeachApi_Tool.json` example that could be used in the langflow.store. What do you think?

**Comment by ogabrielluiz** [comment]
We could add it to the store and make some buzz around it. What do you think? If you use Slack we could connect there.

**Pull request merged**
