### PR TITLE
[New feature] Add support for Amazon Bedrock, Amazon Kendra

### PR DESCRIPTION
**Pull request by ysekiy**
This pull request is to support for two new services - Amazon Bedrock and Amazon Kendra, expanding the capabilities of our langflow application

## related issue
- https://github.com/logspace-ai/langflow/issues/1050
- https://github.com/logspace-ai/langflow/issues/1051

### CODE REVIEW

**Comment by ysekiy** [comment]
Thank you!

**Review by rodzanto — APPROVED** [review]
Good to go

**Comment by ysekiy** [comment]
Hi @ogabrielluiz,

Thank you for your response.

> take a look at the comments I left a few days ago?

Could you add a link or more detailed guidance?
I saw this [mesage](https://github.com/logspace-ai/langflow/pull/1045#pullrequestreview-1679908368) but I couldn't get what should I do for us.

Sorry for causing you trouble. And I also appreciate for your support.

Thanks,
Yuki

**Comment by ogabrielluiz** [comment]
The only thing is that you probably copy pasted the wrong strings when writing the build_config.

```
"attribute_filter": {
                "attribute_filter": "Attribute Filter",
                "field_type": "code",
            },
```
Should probably be:
```
"attribute_filter": {
                "display_name": "Attribute Filter",
                "field_type": "code",
            },
```

**Comment by rabalasubramani3** [comment]
When cn we expect this released?

**Comment by ysekiy** [comment]
Hi @ogabrielluiz ,

Thank you for your comment. modified. Could you approve this?

**Review by ogabrielluiz — APPROVED** [review]
LGTM

**Pull request merged**
