### PR TITLE
Add possibility to change csv separator on chat modal.

### PR DESCRIPTION
**Pull request by Cristhianzl**
📝 (IOOutputView/index.tsx): import lodash's cloneDeep function to be used later in the code
✨ (IOOutputView/index.tsx): add support for Select component to choose CSV separator
♻️ (IOOutputView/index.tsx): refactor handleChangeSelect function to update flowPoolNode data and setFlowPool state
📝 (csvOutputComponent/index.tsx): import useFlowStore from flowStore to access flowPool state
♻️ (csvOutputComponent/index.tsx): refactor CsvOutputComponent to use flowPool state instead of csvNode prop

### CODE REVIEW

**Review by anovazzi1 — CHANGES_REQUESTED** [review]
please check this css white gap on the right:
image

**Comment by Cristhianzl** [comment]
@anovazzi1 
Thanks for your feedback.
Here's the print of the data-grid with the css adjustments.
image

**Comment by Cristhianzl** [comment]
@anovazzi1 
Thanks for your feedback.
Here's a print of the data-grid with the adjustments.
image

**Review by anovazzi1 — APPROVED** [review]
LGTM

**Pull request merged**
