### PR TITLE
Streaming, Chat Markdown, and CacheManager

### LINKED ISSUE #162: Support stream output
support stream output like chatgpt, otherwise the waiting time is too long when outputting long text
tks!

### LINKED ISSUE #241: Markdown formatting not rendered in chat interface
**Describe the bug**

Although the OpenAI chat models create output with markdown formatting characters, this is not rendered by the langflow chat window. Rendering the markdown is important for the readability of code out.

**To Reproduce**

Ask an OpenAI chat model to output code.

**Screenshots**

Screenshot 2023-05-03 at 20 58 27

### PR DESCRIPTION
**Pull request by ogabrielluiz**
Chat now has Markdown helping see code blocks and images.

Now models stream their messages if possible (VectorStores don't allow async for now in LangChain, I think)

We added a cache_manager object. This allows you to add images (and soon other things too) to the chat. You can also recall the object saved from another PythonFunction node.

Closes #241
Closes #162

### CODE REVIEW

**Comment by lucaseduoli** [comment]
Dev merge on Streaming not working successfully. Is there a significant change at the Flow page on the streaming branch? If not, can you revert that commit so that I can merge it again please?

**Comment by lucaseduoli** [comment]
@ogabrielluiz Dev merge on Streaming not working successfully. Is there a significant change at the Flow page on the streaming branch? If not, can you revert that commit so that I can merge it again please?

**Comment by ogabrielluiz** [comment]
Done. I think it is good to go.

**Comment by lucaseduoli** [comment]
LGTM!

**Pull request merged**
