### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by anovazzi1**
# Major Changes
- Added descriptions to the flows to provide more context.
- Sorted some context providers to improve readability and organization.
- Implemented error handling for the entire application to ensure smoother operation.
- Added a reset state feature to the application in the event of an error.
- Created new UI components for the export and import flows to enhance user experience.
- Implemented a feature to automatically remove API keys during the export flow for added security.

### CODE REVIEW

**Review by ogabrielluiz — COMMENTED** [review]
Good. We should try to show that something went wrong whenever this code run.

**Comment by anovazzi1** [comment]
> Good. We should try to show that something went wrong whenever this code run.

For any generic error, but not the ones that can break the app?

**Comment by ogabrielluiz** [comment]
> > Good. We should try to show that something went wrong whenever this code run.
> 
> For any generic error, but not the ones that can break the app?

If this Icon check fails and the node isn't loaded. Maybe we should just show a toast telling that Node X failed to load or something like that.

**Comment by anovazzi1** [comment]
> > > Good. We should try to show that something went wrong whenever this code run.
> > 
> > For any generic error, but not the ones that can break the app?
> 
> If this Icon check fails and the node isn't loaded. Maybe we should just show a toast telling that Node X failed to load or something like that.

right, I think that can be done 😁

**Pull request merged**
