### PR TITLE
Allow users to use dark mode

### PR DESCRIPTION
**Pull request by brylie**
Related to #1115 

It is nice to allow users to choose light or dark mode based on their own needs, such as sensitivity to bright light.

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
Hey @brylie 
Thanks for the PR.

Could you check that all the pages in the docs work well in Dark mode, please? This is probably the reason we have that deactivated.

**Comment by brylie** [comment]
The dark mode works overall, but isn't 100% covered. For example there are some page elements that have light backgrounds (pictured below.) However, having most things in dark mode is a significant improvement to reducing eye strain even when a few items still remain with light background. So, I'd urge the team to not let perfect be the enemy of good on this PR and consider it as an incremental step towards proper dark mode support.

## Code blocks and inline code use GitHub Light theme

image

image

**Comment by brylie** [comment]
Leaving the dark/light toggle enabled and switching to `github-dark` mode for the code and inline code panels seems like a good compromise.

image

image

**Review by ogabrielluiz — APPROVED** [review]
LGTM

**Pull request merged**
