### PR TITLE
🐛 fix(utils.ts): fix typo in utils.ts

### PR DESCRIPTION
**Pull request by eltociear**
HugginFaceIcon -> HuggingFaceIcon

### CODE REVIEW

**Review by ogabrielluiz — CHANGES_REQUESTED** [review]
Hey. Thanks for the PR! 

You forgot to upgrade the name where it is defined in the icons folder.

**Comment by ogabrielluiz** [comment]
Hi, @eltociear. Are you planning on addressing those changes soon?

**Comment by eltociear** [comment]
@ogabrielluiz Sorry! I have now corrected the commit message as well.

**Comment by ogabrielluiz** [comment]
Hey.
You still haven't changed the names in the icons folder.

**Comment by eltociear** [comment]
@ogabrielluiz Sorry, I misunderstood.
The files in the `icons` folder have also been corrected.

**Comment by ogabrielluiz** [comment]
Awesome. Thanks!

**Pull request merged**
