### PR TITLE
migrating to Vite

### PR DESCRIPTION
**Pull request by gsaivinay**
This PR implements #264

### Changes done

- Organized package.json for dev only dependencies.
- Removed react-scripts and added Vite and its dependencies.
- Refactored `require` with `import` in few places.

### Changes to development process

- Most of the development workflow is unchanged with this migration.
- For any API call to backend, the path must be added in the `vite.config.ts` so that vite server can forward it to backend server via proxy. This can be standardized with naming conventions so that we can simply configure regular expressions and forget about it.

### Testing

- [x] Build and test
- [x] Run dev servers and test

### CODE REVIEW

**Comment by ogabrielluiz** [comment]
This looks great! 
I ran `make build` and installed LangFlow with pip. Ran smoothly here. 

The proxies still aren't clear to me. 

We used fetch because if we deployed it as static files in HuggingFace Spaces it would use the hf.space URL. We only had to set proxies for development. What changes in that regard?

**Comment by gsaivinay** [comment]
The change would be only in terms of dev server run, but nothing would change if we were running the app as SPA via static file serving with the final build.

Basically, with Vite server, when we define a proxy server for backend, we also need to define what API paths we need to forward to proxy server. If you refer to `src/frontend/vite.config.ts` line 4, there I've added what routes we want to forward to proxy server. We can also define a regular expression path like in line 7 and 8 in the same file.

**Comment by ClaraLeigh** [comment]
Ty for this, I was having out of memory compile issues in the front end (Mac M1 Pro), but using vite solved it <3

**Comment by ogabrielluiz** [comment]
We'll finish this release and we'll merge this PR

**Comment by gsaivinay** [comment]
I've tried to rebase to resolve conflicts.

**Pull request closed without merging**
